{
 "title": "Crypto",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Avg price variations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 21, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(Name) (price_change{job=\"crypto\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query count",
   "type": "stat",
   "description": "Total count of query invocations",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "query_count_total{job=\"crypto\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 5 movers",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "topk(5, price_change{job=\"crypto\"})",
     "legendFormat": "{{ ID }}|{{ Name }}"
    }
   ]
  }
 ]
}