global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'crypto'
    metrics_path: '/'
    static_configs:
      - targets: ['crypto-exporter:8000']
